name: Build HBC

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc
    name: Build using devkitPPC via Docker
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt update && \
        sudo apt install -y gcc sox gettext libpng-dev xxd python3-pip
        pip install pycryptodome
    - name: Build WiiPAX
      run: |
        cd wiipax
        make
    - name: Build HBC
      run: |
        cd channel
        make
    - name: Publish WAD
      uses: actions/upload-artifact@v4
      with:
        path: "channel/title/channel_retail.wad"
        name: The Homebrew Channel (WAD, LULZ)
    - name: Publish ELF
      uses: actions/upload-artifact@v4
      with:
        path: "channel/channelapp/channelapp-channel.elf"
        name: The Homebrew Channel (ELF, LULZ)
    - name: Publish DOL
      uses: actions/upload-artifact@v4
      with:
        path: "channel/channelapp/channelapp-channel.dol"
        name: The Homebrew Channel (DOL, LULZ)

      
