name: Build HBC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc
    name: Build using devkitPPC via Docker
    steps:
    - uses: actions/checkout@v4
    - name: Retrieve Common Key from Secret
      shell: bash
      env:
        WII_COMMON_KEY: ${{ secrets.WII_COMMON_KEY }}
      run: |
        mkdir ~/.wii/
        echo $WII_COMMON_KEY | base64 --decode > ~/.wii/common-key
    - name: Install Dependencies
      run: |
        sudo apt update && \
        sudo apt install -y gcc sox gettext libpng-dev xxd python2
    - name: Install pip2 and Python Dependencies
      run: |
        curl https://bootstrap.pypa.io/pip/2.7/get-pip.py | python2
        pip2 install pycryptodomex
    - name: Build WiiPAX
      run: |
        cd wiipax
        make
    - name: Build HBC
      run: |
        cd channel
        make
    - name: Publish WAD
      uses: actions/upload-artifact@v4
      with:
        path: "channel/title/channel_retail.wad"
        name: The Homebrew Channel
